name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # Node versions list
      matrix:
        node-version: [18.x]
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
      - run: make say-hello